# Generated by Django 4.2.23 on 2025-07-21 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='featured_image',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='featured_image_url',
            field=models.URLField(blank=True, help_text='Supabase storage URL for featured image'),
        ),
    ]
