# Generated by Django 4.2.23 on 2025-07-31 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='notification_type',
            field=models.CharField(choices=[('order_update', 'Order Update'), ('inquiry_response', 'Inquiry Response'), ('new_artwork', 'New Artwork'), ('price_drop', 'Price Drop'), ('exhibition', 'Exhibition Notice'), ('newsletter', 'Newsletter')], max_length=20),
        ),
    ]
