# Generated by Django 4.2.23 on 2025-09-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0002_alter_usernotification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='save_payment_info',
            field=models.BooleanField(default=False, help_text='User opted to save payment info'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='Stripe customer ID', max_length=100, null=True),
        ),
    ]
