# Generated by Django 4.2.23 on 2025-07-21 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('medium', models.CharField(choices=[('watercolor', 'Watercolor'), ('oil', 'Oil'), ('mixed', 'Mixed Media'), ('digital', 'Digital'), ('acrylic', 'Acrylic')], max_length=20)),
                ('dimensions_width', models.DecimalField(decimal_places=2, help_text='Width in inches', max_digits=6)),
                ('dimensions_height', models.DecimalField(decimal_places=2, help_text='Height in inches', max_digits=6)),
                ('year_created', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('inspiration', models.TextField(blank=True, help_text='Story behind the artwork')),
                ('technique_notes', models.TextField(blank=True, help_text='Technical details about creation')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('reserved', 'Reserved'), ('exhibition', 'In Exhibition'), ('private_collection', 'Private Collection')], default='available', max_length=20)),
                ('is_original', models.BooleanField(default=True)),
                ('allows_prints', models.BooleanField(default=True)),
                ('primary_image', models.ImageField(upload_to='artwork/images/')),
                ('detail_image_1', models.ImageField(blank=True, null=True, upload_to='artwork/images/')),
                ('detail_image_2', models.ImageField(blank=True, null=True, upload_to='artwork/images/')),
                ('process_image_1', models.ImageField(blank=True, help_text='Work in progress shots', null=True, upload_to='artwork/process/')),
                ('process_image_2', models.ImageField(blank=True, null=True, upload_to='artwork/process/')),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('alt_text', models.CharField(help_text='Alt text for primary image', max_length=125)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_featured', 'display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='artwork.category')),
            ],
            options={
                'verbose_name_plural': 'Series',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ArtworkInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('message', models.TextField()),
                ('inquiry_type', models.CharField(choices=[('purchase', 'Purchase Inquiry'), ('general', 'General Question'), ('print', 'Print Inquiry')], default='general', max_length=20)),
                ('is_responded', models.BooleanField(default=False)),
                ('response_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='artwork.artwork')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='artwork',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='artwork.category'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artworks', to='artwork.series'),
        ),
        migrations.CreateModel(
            name='ArtworkView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='artwork.artwork')),
            ],
            options={
                'indexes': [models.Index(fields=['artwork', 'timestamp'], name='artwork_art_artwork_3e7a30_idx')],
            },
        ),
    ]
