# Generated by Django 4.2.23 on 2025-07-21 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='detail_image_1',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='detail_image_2',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='primary_image',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='process_image_1',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='process_image_2',
        ),
        migrations.AddField(
            model_name='artwork',
            name='detail_image_1_url',
            field=models.URLField(blank=True, help_text='Additional detail image'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='detail_image_2_url',
            field=models.URLField(blank=True, help_text='Additional detail image'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='lumaprints_product_id',
            field=models.CharField(blank=True, help_text='Lumaprints product ID for prints', max_length=100),
        ),
        migrations.AddField(
            model_name='artwork',
            name='primary_image_url',
            field=models.URLField(default='https://via.placeholder.com/800x600?text=Artwork', help_text='Supabase storage URL for primary image'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='prints_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='process_image_1_url',
            field=models.URLField(blank=True, help_text='Work in progress shots'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='process_image_2_url',
            field=models.URLField(blank=True, help_text='Work in progress shots'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='artworkview',
            name='artwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artwork_views', to='artwork.artwork'),
        ),
    ]
