# Generated by Django 4.2.23 on 2025-07-31 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0002_remove_artwork_detail_image_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('color', models.CharField(default='#6B7280', help_text='Hex color for tag display', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='allows_prints',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='detail_image_1_url',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='detail_image_2_url',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='is_original',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='price',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='primary_image_url',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='process_image_1_url',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='process_image_2_url',
        ),
        migrations.AddField(
            model_name='artwork',
            name='detail_images',
            field=models.JSONField(blank=True, default=list, help_text='Array of detail image URLs'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='edition_info',
            field=models.CharField(blank=True, help_text='Edition information (limited edition, etc.)', max_length=200),
        ),
        migrations.AddField(
            model_name='artwork',
            name='favorites',
            field=models.PositiveIntegerField(default=0, help_text='Number of times added to wishlist'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='framed_images',
            field=models.JSONField(blank=True, default=list, help_text='Array of framed/context image URLs'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='lifestyle_images',
            field=models.JSONField(blank=True, default=list, help_text='Array of lifestyle/room setting image URLs'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='main_image_url',
            field=models.URLField(default='https://via.placeholder.com/800x600?text=Artwork', help_text='Primary artwork image URL'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='original_available',
            field=models.BooleanField(default=True, help_text='Is original artwork available for sale'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price for original artwork', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='story',
            field=models.TextField(blank=True, help_text='Personal story behind the artwork'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='prints_available',
            field=models.BooleanField(default=True, help_text='Are prints available for this artwork'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='artworks', to='artwork.tag'),
        ),
        migrations.CreateModel(
            name='PrintOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(help_text="e.g., '8x10', '11x14', '16x20'", max_length=20)),
                ('material', models.CharField(help_text="e.g., 'Fine Art Paper', 'Canvas Print'", max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField(blank=True, help_text='Additional details about this print option')),
                ('is_available', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_options', to='artwork.artwork')),
            ],
            options={
                'ordering': ['artwork', 'display_order', 'price'],
                'unique_together': {('artwork', 'size', 'material')},
            },
        ),
    ]
