# Generated by Django 4.2.23 on 2025-08-06 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0003_tag_remove_artwork_allows_prints_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='detail_images',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='framed_images',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='lifestyle_images',
        ),
        migrations.AddField(
            model_name='artwork',
            name='frame1_image_url',
            field=models.URLField(blank=True, default='', help_text='First frame variant image URL'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='frame2_image_url',
            field=models.URLField(blank=True, default='', help_text='Second frame variant image URL'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='frame3_image_url',
            field=models.URLField(blank=True, default='', help_text='Third frame variant image URL'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='frame4_image_url',
            field=models.URLField(blank=True, default='', help_text='Fourth frame variant image URL'),
        ),
    ]
