# Generated by Django 4.2.23 on 2025-08-07 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0004_remove_artwork_detail_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Alt text for primary image', max_length=125),
        ),
    ]
