# Generated by Django 4.2.23 on 2025-08-15 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0005_alter_artwork_alt_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='type',
            field=models.CharField(choices=[('shop', 'Shop'), ('gallery', 'Gallery')], default='shop', help_text='Display type - Shop or Gallery', max_length=20),
        ),
    ]
