# Generated by Django 4.2.23 on 2025-08-16 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0006_artwork_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='status',
        ),
    ]
