# Generated by Django 4.2.23 on 2025-08-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0007_auto_20250815_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='type',
            field=models.CharField(choices=[('original', 'Original'), ('print', 'Print'), ('gallery', 'Gallery')], default='original', help_text='Artwork type - Original, Print, or Gallery', max_length=20),
        ),
    ]
