# Generated by Django 4.2.23 on 2025-08-19 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0008_alter_artwork_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='original_available',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='prints_available',
        ),
        migrations.AlterField(
            model_name='artwork',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Price for original artwork (required when type is 'original')", max_digits=10, null=True),
        ),
    ]
