# Generated by Django 4.2.23 on 2025-08-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0009_remove_availability_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='original_available',
            field=models.BooleanField(default=True, help_text='Whether the original artwork is available for purchase'),
        ),
    ]
