# Generated by Django 4.2.23 on 2025-08-29 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0008_add_performance_indexes'),
        ('artwork', '0010_add_original_available_field'),
    ]

    operations = [
    ]
