# Generated by Django 4.2.23 on 2025-08-29 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0011_merge_20250829_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='_cached_image_url',
            field=models.URLField(blank=True, help_text='Cached resolved image URL'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='_cached_thumbnail_url',
            field=models.URLField(blank=True, help_text='Cached thumbnail URL'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='_url_cache_expires',
            field=models.DateTimeField(blank=True, help_text='When cached URLs expire', null=True),
        ),
    ]
