# Generated by Django 4.2.23 on 2025-08-29 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0012_add_url_caching'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='_cached_image_url',
            field=models.TextField(blank=True, help_text='Cached resolved image URL'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='_cached_thumbnail_url',
            field=models.TextField(blank=True, help_text='Cached thumbnail URL'),
        ),
    ]
