# Generated by Django 4.2.23 on 2025-08-29 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0013_fix_url_field_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='_cached_frame_urls',
            field=models.JSONField(blank=True, default=dict, help_text='Cached frame image URLs'),
        ),
    ]
