# Generated by Django 4.2.23 on 2025-09-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0015_add_performance_indexes_comprehensive'),
    ]

    operations = [
        # Allow NULL values and provide defaults for cache fields
        migrations.AlterField(
            model_name='artwork',
            name='_cached_image_url',
            field=models.URLField(blank=True, null=True, default='', help_text='Cached resolved image URL'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='_cached_thumbnail_url',
            field=models.URLField(blank=True, null=True, default='', help_text='Cached thumbnail URL'),
        ),
        # _url_cache_expires and _cached_frame_urls already allow NULL from previous migrations
    ]