# Generated by Django 4.2.23 on 2025-09-12 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0016_fix_cache_field_constraints'),
    ]

    operations = [
    ]
