# Generated by Django 4.2.23 on 2025-09-12 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0017_auto_20250911_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='_cached_image_url',
            field=models.TextField(blank=True, default='', help_text='Cached resolved image URL'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='_cached_thumbnail_url',
            field=models.TextField(blank=True, default='', help_text='Cached thumbnail URL'),
        ),
    ]
