# Generated by Django 4.2.23 on 2025-09-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0018_alter_artwork__cached_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CacheMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('hit', 'Cache Hit'), ('miss', 'Cache Miss'), ('warming_success', 'Cache Warming Success'), ('warming_failure', 'Cache Warming Failure'), ('refresh_proactive', 'Proactive Refresh'), ('refresh_reactive', 'Reactive Refresh'), ('api_call', 'External API Call'), ('thread_pool_task', 'Thread Pool Task')], max_length=20)),
                ('artwork_id', models.IntegerField(blank=True, null=True)),
                ('response_time_ms', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['metric_type', 'timestamp'], name='artwork_cac_metric__5255fb_idx'), models.Index(fields=['artwork_id', 'timestamp'], name='artwork_cac_artwork_cdc675_idx'), models.Index(fields=['timestamp'], name='artwork_cac_timesta_aaa52d_idx')],
            },
        ),
    ]
