# Generated by performance optimization for sub-3s load times
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0020_add_performance_indexes_critical'),
    ]

    operations = [
        # Composite indexes for common query patterns
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_artwork_active_featured_order ON artwork_artwork(is_active, is_featured, display_order, created_at);",
            "DROP INDEX IF EXISTS idx_artwork_active_featured_order;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_artwork_type_active_price ON artwork_artwork(type, is_active, original_price);",
            "DROP INDEX IF EXISTS idx_artwork_type_active_price;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_artwork_category_active ON artwork_artwork(category_id, is_active, is_featured);",
            "DROP INDEX IF EXISTS idx_artwork_category_active;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_artwork_medium_active_featured ON artwork_artwork(medium, is_active, is_featured);",
            "DROP INDEX IF EXISTS idx_artwork_medium_active_featured;"
        ),
        # Index for cache expiry queries
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_artwork_cache_expiry ON artwork_artwork(_url_cache_expires) WHERE _url_cache_expires IS NOT NULL;",
            "DROP INDEX IF EXISTS idx_artwork_cache_expiry;"
        ),
        # Index for image URL queries
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_artwork_main_image ON artwork_artwork(main_image_url) WHERE main_image_url != '';",
            "DROP INDEX IF EXISTS idx_artwork_main_image;"
        ),
    ]