# Generated by Django 4.2.23 on 2025-07-31 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='commission_specifications',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item_type',
            field=models.CharField(choices=[('original', 'Original Artwork'), ('print', 'Print'), ('shipping', 'Shipping'), ('tax', 'Tax')], default='original', max_length=20),
        ),
    ]
