# Generated by Django 4.2.23 on 2025-08-12 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='luma_prints_order_id',
            field=models.CharField(blank=True, help_text='Luma Prints Order ID', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_charge_id',
            field=models.CharField(blank=True, help_text='Stripe Charge ID', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, help_text='Stripe PaymentIntent ID', max_length=100),
        ),
    ]
