# Generated by Django 4.2.23 on 2025-09-09 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_luma_prints_order_id_order_stripe_charge_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='carrier',
            field=models.CharField(blank=True, help_text='Shipping carrier (UPS, FedEx, USPS, etc.)', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_delivery',
            field=models.DateTimeField(blank=True, help_text='Estimated delivery date', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='luma_prints_status',
            field=models.CharField(blank=True, help_text='Status from LumaPrints', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='luma_prints_tracking_url',
            field=models.URLField(blank=True, help_text='LumaPrints tracking URL'),
        ),
        migrations.AddField(
            model_name='order',
            name='luma_prints_updated_at',
            field=models.DateTimeField(blank=True, help_text='Last update from LumaPrints', null=True),
        ),
    ]
